server.port: 3002
spring.application.name: composite

services:
  post: http://post/api/v1/
  user: http://user/api/v1/

healthurl:
  post: http://post/actuator/health
  user: http://user/actuator/health

api:
  common:
    version: 1.0.0
    title: Social App Composite Service
    description: Rest API Defenition for Social App Composite Service
    termsOfServiceUrl: MINE TERMS OF SERVICE URL
    license: MIT
    licenseUrl: https://github.com/renganatha10

    contact:
      name: Renganatha A
      url: https://github.com/renganatha10
      email: renganatha10@gmail.com

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

ribbon.ServerListRefreshInterval: 5000
ribbon.NFLoadBalancerPingInterval: 5

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

---

spring.profiles: docker

server.port: 8080

eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/