
server.port: 3000
spring.application.name: social-app
spring.h2.console.enabled: true
spring.datasource.url: jdbc:postgresql://localhost:5432/fb_app
spring.datasource.username: renganatha
spring.datasource.password:

spring:
    jpa:
        show-sql: true
        properties:
            hibernate:
                ddl-auto: validate
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
                generate_statistics: true

logging:
  level:
    org.springframework:
        jdbc:
            core:
                JdbcTemplate: DEBUG
                StatementCreatorUtils: TRACE

api:
  common:
    version: 1.0.0
    title: Social App
    description: Rest API Defenition for Social App
    termsOfServiceUrl: MINE TERMS OF SERVICE URL
    license: MIT
    licenseUrl: https://github.com/renganatha10

    contact:
      name: Renganatha A
      url: https://github.com/renganatha10
      email: renganatha10@gmail.com
